file_format: "1"
id: dana58
name: dana58
type: shield
url: https://github.com/rchristof/zmk-config-dana58
requires: [nice_nano_v2]
exposes: [i2c_oled]
features:
  - keys
  - display
siblings:
  - dana58_left
  - dana58_right